[package]
name = "uindex"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = "thin"
incremental = true

[dependencies]
itertools = "0.13.0"
libdivsufsort-rs = "0.1.3"
mem_dbg = "0.2.4"
minimizers = { version = "0.1.0", git = "https://github.com/ragnargrootkoerkamp/minimizers", default-features = false}
num-traits = "0.2.19"
sux = "0.4.4"
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Optional for python bindings
pyo3 = { version = "0.22.2", features = ["extension-module"], optional = true }

# Also used via python interface.
rand = "0.8.5"
needletail = "0.5.1"
# fxhash = "0.2.1"
# size = "0.4.1"
# rayon = "1.10.0"

[patch.crates-io]
mem_dbg = { path = "../forks/mem_dbg-rs/mem_dbg" }

[dev-dependencies]
