[package]
name = "uindex"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = "thin"
incremental = true

[dependencies]
cacheline-ef = { git = "https://github.com/ragnargrootkoerkamp/cacheline-ef" }
itertools = "0.13.0"
libdivsufsort-rs = "0.1.4"
libsais-rs = { version = "0.1.0", git = "https://github.com/ragnargrootkoerkamp/libsais-rs"}
mem_dbg = "0.2.4"
minimizers = { version = "0.1.0", git = "https://github.com/ragnargrootkoerkamp/minimizers", default-features = false}
packed-seq = { version = "0.1.0", git = "https://github.com/rust-seq/packed-seq" }
sdsl-lite-fm = { version = "0.1.0", path = "../sdsl-lite-fm" }
num-traits = "0.2.19"
sux = "0.4.4"
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
bio = "2.0.3"
# bio = { version = "2.0.3", path = "../forks/rust-bio" }
awry = "0.2"

# Optional for python bindings
pyo3 = { version = "0.22.2", features = ["extension-module"], optional = true }

# Also used via python interface.
rand = "0.8.5"
needletail = "0.6.1"
color-backtrace = "0.6.1"
serde_json = "1.0.135"
# fxhash = "0.2.1"
# size = "0.4.1"
# rayon = "1.10.0"

[dev-dependencies]

[features]
# Enable python bindings
python-bindings = ['dep:pyo3']

# Not enabled by default, since MacOS doesn't have OpenMP.
openmp = ['libsais-rs/openmp']

default = ['python-bindings']
