[package]
name = "uindex"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = "thin"
incremental = true

[dependencies]
itertools = "0.13.0"
libdivsufsort-rs = "0.1.3"
minimizers = { version = "0.1.0", git = "https://github.com/ragnargrootkoerkamp/minimizers"}

# cacheline-ef = { path = "../cacheline-ef" }
# fxhash = "0.2.1"
# size = "0.4.1"
# sux = { version = "0.4.1", git = "https://github.com/vigna/sux-rs" }
# rayon = "1.10.0"

[dev-dependencies]
needletail = "0.5.1"
rand = "0.8.5"
